### ISSUE TITLE
Canvas gets padding from bottom when used in an app with toolbar as action bar

### ISSUE THREAD

**Issue by n0m0r3pa1n** [raydac/jhexed#1]
I have an activity which has a toolbar as an action bar. And I have a fragment which contains the JHexedPhotoView.. The canvas calculations include the action bar width which is at the top and makes a padding at the bottom of the hexes, which is empty. Is there any fix for this? I have been debugging this for hours...
![device-2015-07-23-201146](https://cloud.githubusercontent.com/assets/2341201/8856997/14609ce6-3177-11e5-858a-a14ad152a6b7.png) This is how it looks with an invisible textview above it.
![device-2015-07-23-201320](https://cloud.githubusercontent.com/assets/2341201/8857009/48e2a46e-3177-11e5-9e0e-6bda60f7152a.png) This is how it looks without the textview.

**Comment by n0m0r3pa1n** [comment]
It happens when I change the targetSDK above 13. That means that from ICE_CREAM_SANDWICH something is changed may be in the canvas and it adds padding to it.

**Comment by n0m0r3pa1n** [comment]
The fix is to disable the hardware acceleration for the view. You can use:
setLayerType(View.LAYER_TYPE_SOFTWARE, null); for the view in the constructor or disable it for the whole app in the manifest. http://developer.android.com/guide/topics/graphics/hardware-accel.html

**Comment by raydac** [comment]
cool! thank you very much for the info!
